version: "1"
services:
  - type: web
    name: gestionale-termoidraulico-frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: "https://gestionale-termoidraulico-api.onrender.com/api"
    autoDeploy: true
